import type { NextPage } from 'next';
import Head from 'next/head';
import Navigation from '../../components/Navigation';
import Projects from '../../components/Projects';


type props = {

}

const Page_Projects: NextPage<props> = ({

}) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <Projects />
      </main>
    </div>
  )
}

export default Page_Projects;
