import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import Logo from '../components/Logo';
import Main from '../components/Main';
import Navigation from '../components/Navigation';
import useWindowDimensions from '../lib/useWindowDimensions';


type props = {

}

const Page_Home: NextPage<props> = ({

}) => {
  const [activeSection, setActiveSection] = useState(0);
  const { width, height } = useWindowDimensions();

  setTimeout(() => {setActiveSection((activeSection + 1) % 3)}, 3000);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation 
          activeSection={activeSection}
          width={width}
          />
        <Logo 
          activeSection={activeSection }
          width={width}
        />
        <Main 
          activeSection={activeSection}
          setActiveSection={setActiveSection}
        />
      </main>
    </div>
  )
}

export default Page_Home;
