import type { NextPage } from 'next';
import Head from 'next/head';
import Logo from '../components/Logo';
import Main from '../components/Main';
import Navigation from '../components/Navigation';


type props = {

}

const Page_Home: NextPage<props> = ({

}) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <Logo />
        <Main />
      </main>
    </div>
  )
}

export default Page_Home;
