import { useViewportScroll } from 'framer-motion';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Logo from '../components/Logo';
import Main from '../components/Main';
import Navigation from '../components/Navigation';
import useWindowDimensions from '../lib/useWindowDimensions';


type props = {

}

const Page_Home: NextPage<props> = ({

}) => {
  const [activeSection, setActiveSection] = useState(0);
  const { width, height } = useWindowDimensions();

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  });

  const handleScroll = (e: Event) => {
    let section: number;

    let scroll = window.scrollY
    console.log(scroll);

    if (scroll < 1) {
      section = 0;
    } else {
      section = 1;
    }

    if (activeSection !== section) setActiveSection(section);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation 
          activeSection={activeSection}
          width={width}
          />
        <Logo 
          activeSection={activeSection}
          width={width}
        />
        <Main 
          activeSection={activeSection}
          setActiveSection={setActiveSection}
        />
      </main>
    </div>
  )
}

export default Page_Home;
